#! /bin/bash
# mothurOptiClustLOO.sh
# Begum Topcuoglu
# William L. Close
# Schloss Lab
# University of Michigan

##################
# Set Script Env #
##################

# Set the variables to be used in this script
SHARED=${1:?ERROR: Need to define SHARED.}
SAMPLE=${2:?ERROR: Need to define SAMPLE.}

# Other variables
OUTDIR=data/process/opticlust/loo/"${SAMPLE}"/ # Output dir based on sample name to keep things separate during parallelization/organized
NPROC=$(nproc) # Setting number of processors to use based on available resources


########################################
# Removing All Except Specified Sample #
########################################

# Make output dirs if they don't exist
mkdir -p "${OUTDIR}"/

# Removing old files if they exist
if [ -n "$(ls -A "${OUTDIR}")" ]; then
	rm "${OUTDIR}"/*
fi

# Create cluster distance file for individual sample
mothur "#set.current(outputdir="${OUTDIR}"/, processors="${NPROC}");
	get.groups(shared="${SHARED}", groups="${SAMPLE}")"

# Removing file generated by set.current()
rm "${OUTDIR}"/current_files.summary

# Renaming outputs of files generated from single sample
REPLACEMENT=$(echo "${OUTDIR}"/glne.opticlust.opti_mcc.0.03.subsample.0.03.pick.shared | sed "s:\(.*/\).*:\1"${SAMPLE}".in.opti_mcc.0.03.subsample.shared:")
mv "${OUTDIR}"/glne.opticlust.opti_mcc.0.03.subsample.0.03.pick.shared "${REPLACEMENT}"



############################
# Removing Specific Sample #
############################

# Create cluster distance file for individual sample
mothur "#set.current(outputdir="${OUTDIR}"/, processors="${NPROC}");
	remove.groups(shared="${SHARED}", groups="${SAMPLE}")"

# Removing file generated by set.current()
rm "${OUTDIR}"/current_files.summary

# Renaming outputs of files generated from single sample
REPLACEMENT=$(echo "${OUTDIR}"/glne.opticlust.opti_mcc.0.03.subsample.0.03.pick.shared | sed "s:\(.*/\).*:\1"${SAMPLE}".out.opti_mcc.0.03.subsample.shared:")
mv "${OUTDIR}"/glne.opticlust.opti_mcc.0.03.subsample.0.03.pick.shared "${REPLACEMENT}"
