__default__:
  jobname: "{rule}.{wildcards}"
  nodes: 1
  ntasks: 1
  mempercpu: "6GB"
  time: "15:00"
  account: "pschloss99"
  partition: "standard"
  mailuser: "armourc@umich.edu"
  mailtype: "FAIL"
  output: "logs/slurm/%x-%j.out"



##################################################################
#
# Analysis
#
##################################################################

getSRASequences:
  time: "45:00"

get16SReferences:
  ntasks: 4

preclusterSequences:
  ntasks: 12
  time: "12:00:00"

clusterOptiClust:
  ntasks: 12
  time: "8:30:00"

make8020splits:
  time: "1:00:00"

plot8020splits:
  time: "1:00:00"
  
generateOptiClustData:
  ntasks: 12
  time: "5:00:00"

clusterOptiFitData:
  ntasks: 12
  time: "8:00:00"
  
fitOptiFit:
  ntasks: 12
  time: "8:00:00"

runOptiClustModels:
  ntasks: 12
  time: "72:00:00"

runOptiFitModels:
  ntasks: 12
  time: "72:00:00"