__default__:
  jobname: "{rule}.{wildcards}"
  nodes: 1
  ntaskspernode: 1
  cpuspertask: 1
  mempercpu: "6GB"
  time: "15:00"
  account: "pschloss1"
  partition: "standard"
  mailuser: "armourc@umich.edu"
  mailtype: "FAIL"
  output: "logs/slurm/%x-%j.out"



##################################################################
#
# Analysis
#
##################################################################

getSRASequences:
  time: "45:00"

get16SReferences:
  cpuspertask: 4

preclusterSequences:
  cpuspertask: 12
<<<<<<< HEAD
  time: "12:00:00"
=======
  time: "200:00:00"
>>>>>>> 31fa3564199a06b812c6fc4129c1f8b4fa56936d

leaveOneOutOptiFit:
  cpuspertask: 12
  time: "8:30:00"

clusterOptiFit:
  cpuspertask: 12
  time: "6:30:00"

clusterOptiClust:
  cpuspertask: 12
  time: "8:30:00"

predictOptiFitDiagnosis:
  cpuspertask: 2
  time: "1:00:00"

predictOptiClustDiagnosis:
  cpuspertask: 2
  time: "1:00:00"
