__default__:
  jobname: "{rule}.{wildcards}"
  nodes: 1
  ntaskspernode: 1
  cpuspertask: 1
  mempercpu: "4GB"
  time: "15:00"
  account: "ACCOUNT"
  partition: "standard"
  mailuser: "EMAIL"
  mailtype: "END,FAIL"
  output: "logs/slurm/%x-%j.out"



##################################################################
#
# Analysis 
#
##################################################################

getSRASequences:
  time: "30:00"

get16SReferences:
  cpuspertask: 4

preclusterSequences:
  cpuspertask: 12
  time: "3:00:00"

leaveOneOut:
  cpuspertask: 12
  time: "1:30:00"

clusterOptiFit:
  cpuspertask: 4
  time: "30:00"

predictDiagnosis:
  cpuspertask: 2
  time: "30:00"
