cluster: "sbatch --job-name={rule}_{wildcards} 
                 --nodes=1
                 --mem={resources.mem_mb} 
                 --time={resources.time_min} 
                 --account=pschloss1 
                 --partition=standard 
                 --mail-user=armourc@umich.edu 
                 --mail-type=FAIL 
                 -c {resources.ncores} 
                 --output=logs/slurm/%x-%j.out"

# snakemake args
jobs: 100
use-conda: true
verbose: true
keep-going: true
conda-frontend: "mamba"
notemp: true
default-resources: [ncores=1,
                    mem_mb=1000,
                    time_min=15]